[account_analytic_line_no_close_account] 8.0.1.0.1
open-synergy/opnsynid-account-analytic pull request #16
Opened 2022-01-10 06:32 UTC by azmimr67

* Task T/21/005192 - Issue #15
* Tidak boleh merubah analytic line pada analytic account yg sudah di close
* Tidak boleh menghapus analytic line pada analytic account yang sudah di close

2022-01-11 01:01 UTC, mikevhe18 requested changes

2022-01-11 01:01 UTC, mikevhe18 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +        return result
Gunakan looping recordset untuk method write.
```
def write(self, vals):
    for record in self:
    ...
```
Tidak perlu melakukan browse untuk mencari analytic account, bisa langsung menggunakan record
`record.account_id.state == "close":`

2022-01-11 01:01 UTC, mikevhe18 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +                return super(AccountAnalyticLine, self).unlink()
Gunakan looping recordset untuk method write.
```
def unlink(self):
    for record in self:
    ...
```
Tidak perlu melakukan browse untuk mencari analytic account, bisa langsung menggunakan record
`record.account_id.state == "close":`

2022-01-11 14:40 UTC, azmimr67 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +        return result
Mike ... bukankah dilakukan browse dulu?
Sebab state yang akan di cek adalah state di analytic account nya bukan state di analytyc line

2022-01-11 14:41 UTC, azmimr67 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +                return super(AccountAnalyticLine, self).unlink()
Mike ... bukankah dilakukan browse dulu?
Sebab state yang akan di cek adalah state di analytic account nya bukan state di analytyc line

2022-01-13 03:41 UTC, mikevhe18 requested changes

2022-01-13 03:41 UTC, mikevhe18 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +            return result
```
@api.multi
def write(self, vals):
    _super = super(AccountAnalyticLine, self)
    result = _super.write(vals)
    for record in self:
        if record.account_id:
            if record.account_id.state == "close":
                msg_error = _("Cannot Edit -> Analytic account is closed")
                raise UserError(msg_error)
    return result
```

2022-01-13 03:41 UTC, mikevhe18 commented on account_analytic_line_no_close_account/models/account_analytic_line.py
> +                    return super(AccountAnalyticLine, record).unlink()
```
@api.multi
def unlink(self):
    _super = super(AccountAnalyticLine, self)
    result = _super.unlink()
    for record in self:
        if record.account_id:
            if record.account_id.state == "close":
                msg_error = _("Cannot Delete --> Analytic account is closed")
                raise UserError(msg_error)
    return result
```

2022-01-28 00:34 UTC, merged