[8.0][analytic_distribution_mass_assign] Adding new module
open-synergy/opnsynid-account-analytic pull request #2
Opened 2017-02-20 06:11 UTC by mikevhe18

2017-02-21 05:35 UTC, andhit-r requested changes

2017-02-21 05:35 UTC, andhit-r commented on analytic_distribution_mass_assign/tests/test_change_analytic.py
> +            'sequence': 001,
@mikevhe18 ini bener 001? string apa integer?

2017-02-24 01:38 UTC, mikevhe18 commented on analytic_distribution_mass_assign/tests/test_change_analytic.py
> +            'sequence': 001,
Iya mas ini integer bukan string, kalau misalnya string pasti error mas

2017-02-24 03:31 UTC, andhit-r commented on analytic_distribution_mass_assign/tests/test_change_analytic.py
> +            'sequence': 001,
Kenapa ga 1 aja klo begitu? Kenapa 001?

2017-02-24 05:56 UTC, mikevhe18 commented on analytic_distribution_mass_assign/tests/test_change_analytic.py
> +            'sequence': 001,
Oh iya ya, seharusnya cukup 1 aja kalau integer. Oke nanti direvisi mas

2017-02-24 06:06 UTC, andhit-r approved these changes

2017-02-24 06:22 UTC, merged